# Generated by Django 3.2.7 on 2021-09-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textBE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondoc',
            name='json',
            field=models.JSONField(max_length=2000),
        ),
    ]
