# Generated by Django 3.2.7 on 2021-09-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textBE', '0004_alter_jsondoc_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondoc',
            name='json',
            field=models.TextField(unique=True),
        ),
    ]
