# Generated by Django 3.2.7 on 2021-09-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textBE', '0006_auto_20210930_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsondoc',
            old_name='text',
            new_name='document',
        ),
    ]
